name = "Hack Pack"
author = "Hack Club Minecraft Admins"
version = "v1.4.0-17-g9c2d841+1.5.0-stuff"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7417a4f1778a195568aba3bee2f0dcf2dfc984e4356b4e968f19782033d45ddb"

[versions]
forge = "40.2.7"
minecraft = "1.18.2"

[options]
no-internal-hashes = true
